name: MONIOMI
favicon: null
layout_spectrum: 0.8259364471305162
typography_spectrum: 0.26065706042572856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.09934103186242282
  lightness: 0.21596345189027488
  saturation: 0.22168583958409727
  rhythmicContrast: 0.8131482927128673
purpose: []
